### ISSUE TITLE
Adapt get_ functions for use by OpenCPU

### ISSUE THREAD

**Issue by PietrH** [inbo/etnservice#24]
## TODO

Adapt functions:

- [x] get_acoustic_deployments()
- [x] get_acoustic_projects()
- [x] get_acoustic_receivers()
- [x] get_animal_projects()
- [x] list_deployment_ids()
- [x] get_animals()
- [x] get_cpod_projects()
- [x] get_tags()

Adapt tests:
- [x] get_acoustic_deployments()
- [x] get_acoustic_projects()
- [x] get_acoustic_receivers()
- [x] get_animal_projects()
- [x] list_deployment_ids()
- [x] get_animals()
- [x] get_cpod_projects()
- [x] get_tags()

Pass tests:
- [x] get_acoustic_deployments()
- [x] get_acoustic_projects()
- [x] get_acoustic_receivers()
- [x] get_animal_projects()
- [x] list_deployment_ids()
- [x] get_animals()
- [x] get_cpod_projects()
- [x] get_tags()

Add postman tests:
- [x] get_acoustic_deployments()
- [x] get_acoustic_projects()
- [x] get_acoustic_receivers()
- [x] get_animal_projects()
- [x] list_deployment_ids()
- [x] get_animals()
- [x] get_cpod_projects()
- [x] get_tags()

Expand postman tests with response content test:
- [ ] get_acoustic_deployments()
- [ ] get_acoustic_projects()
- [ ] get_acoustic_receivers()
- [ ] get_animal_projects()
- [ ] list_deployment_ids()
- [ ] get_animals()
- [ ] get_cpod_projects()
- [ ] get_tags()
---

- [x] pass tests vliz rstudio
- [x] pass R CMD CHECK

---
- [ ] check postman test results
- [ ] export postman tests
- [ ] commit postman tests to repo using handy tool

**Comment by PietrH** [comment]
tests regarding bad connections will fail because I haven't written a new failstate yet, eg. :
```R

test_that("get_acoustic_deployments() returns error for incorrect connection", {
  expect_error(
    get_acoustic_deployments(credentials = "not_a_credentials"),
    "Not a credentials object to database."
  )
})
```

See #12
