### ISSUE TITLE
Adapt list_ functions for use by OpenGPU

### ISSUE THREAD

**Issue by PietrH** [inbo/etnservice#26]
## TODO

Adapt functions:
- [x] list_acoustic_project_codes
- [x] list_acoustic_tag_ids
- [x] list_animal_ids
- [x] list_animal_project_codes
- [x] list_cpod_project_codes
- [x] list_deployment_ids
- [x] list_receiver_ids
- [x] list_scientific_names
- [x] list_station_names
- [x] list_tag_serial_numbers
- [ ] ~~list_values~~
- [ ] ~~list_network_project_codes~~
- [ ] ~~list_tag_ids~~

Adapt tests:
- [x] list_acoustic_project_codes
- [x] list_acoustic_tag_ids
- [ ] list_animal_ids
- [x] list_animal_project_codes
- [x] list_cpod_project_codes
- [x] list_deployment_ids
- [x] list_receiver_ids
- [x] list_scientific_names
- [x] list_station_names
- [x] list_tag_serial_numbers
- [ ] ~~list_values~~
- [ ] ~~list_network_project_codes~~
- [ ] ~~list_tag_ids~~

Pass tests:

- [x] list_acoustic_project_codes
- [x] list_acoustic_tag_ids
- [x] list_animal_ids
- [x] list_animal_project_codes
- [x] list_cpod_project_codes
- [x] list_deployment_ids
- [x] list_receiver_ids
- [x] list_scientific_names
- [x] list_station_names
- [x] list_tag_serial_numbers
- [x] ~~list_values~~
- [ ] ~~list_network_project_codes~~
- [ ] ~~list_tag_ids~~

Add postman tests:

- [x] list_acoustic_project_codes
- [x] list_acoustic_tag_ids
- [x] list_animal_ids
- [x] list_animal_project_codes
- [x] list_cpod_project_codes
- [x] list_deployment_ids
- [x] list_receiver_ids
- [x] list_scientific_names
- [x] list_station_names
- [x] list_tag_serial_numbers
- [x] ~~list_values~~
- [ ] ~~list_network_project_codes~~
- [ ] ~~list_tag_ids~~

Expand postman tests with response content test:
- [x] list_acoustic_project_codes
- [x] list_acoustic_tag_ids
- [x] list_animal_ids
- [x] list_animal_project_codes
- [x] list_cpod_project_codes
- [x] list_deployment_ids
- [x] list_receiver_ids
- [x] list_scientific_names
- [x] list_station_names
- [x] list_tag_serial_numbers
- [ ] ~~list_values~~
- [ ] ~~list_network_project_codes~~
- [ ] ~~list_tag_ids~~
---

- [ ] pass tests vliz rstudio
- [ ] pass R CMD CHECK

---
- [x] check postman test results
- [x] export postman tests
- [x] commit postman tests to repo using handy tool

**Comment by PietrH** [comment]
`list_values` doesn't use a database connection, thus doesn't need any changes to be used over the api. I'm not sure it makes sense to provide an API version of this function. 

```R
#' List all unique values from a data.frame column
#'
#' Get a vector with all unique values found in a given column of a data.frame.
#' Concatenated values (`A,B`) in the column can be returned as single values
#' (`A` and `B`).
```

**Comment by PietrH** [comment]
`list_animal_ids()` is untested in `etn` main

**Comment by PietrH** [comment]
Should depriciated functions be ported to the API? 

Example; `list_network_project_codes()`

**Comment by PietrH** [comment]
is r cmd check still failing?

**Comment by PietrH** [comment]
R CMD CHECK passes on d924f1f
