### ISSUE TITLE
Adapt write_dwc() for use by OpenCPU

### ISSUE THREAD

**Issue by PietrH** [inbo/etnservice#33]
Like `download_acoustic_dataset()` see #32 `write_dwc()` doesn't exclusivly return an object, if `directory` is not `NULL` it'll write out a csv. 

Unlike `download_acoustic_dataset()`, the handling is more simple for `write_dwc()`. A `project` object is created from `get_animal_projects()` which is used to create an object `dwc_occurrence` which is either returned or written out as csv. 

`dwc_occurrence` is currently created via a locally stored sql query which is edited in place based on the `project` object. Later on we might switch over to darwincore mapping via dplyr similar to inbo/camtraptor#207, but as long as we stick to the sql mapping, it doesn't make much sense to split this function up into multiple requests. 

Thus at least initially, I'll implement this as a single API call that returns `dwc_occurrence`, the client can then either return or write out based on the `directory` argument. 

## TODO

- [x] adapt test-write_dwc.R: expect dwc_occurrence, not csv
- [x] switch over to using credentials
- [x] remove directory argument
- [x] update documentation
- [ ] ~~can we forward messages? progress reports?~~
- [x] remove writing to csv
- [x] pass tests
- [x] pass R CMD CHECK
- [x] #35
-

**Comment by PietrH** [comment]
Currently the function prints a message to console: 
>Reading data and transforming to Darwin Core.


Right after fetching the imis dataset id and title and starting the query to fetch the darwincore occurrence data. This behaviour could be maintained if we split off this first query to the client side.
